name: 'Build Maven Action'
description: 'Build and test a Maven project'

runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Install Maven
      run: sudo apt update && sudo apt install -y maven
      shell: bash

    - name: Build with Maven
      run: mvn clean package -DskipTests=true
      shell: bash