name: Pull Request Opened

on: # trigger conditions
  pull_request:
    types: [opened, synchronize, reopened] # Optionally, trigger on pull requests too

jobs:
  build-pull-request:
    runs-on: mock-project #ubuntu-latest #GitHub hosted - Sharing between

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        
        - name: Build maven
          uses: ./.github/actions/build-maven
          with:
            version: 17
            
        